routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Pages
Route::get('/', 'Frontend\PagesController@home')->name('home');
Route::get('pages/{name}', 'Frontend\PagesController@show')->name('pages');
Route::post('pages/contact', 'Frontend\PagesController@send')->name('contact.send');


Auth::routes();


// Admin
Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
	
	//Analytics
	Route::get('/', 'Backend\AnalyticsController@index')->name('analytics');

	//Pages
	Route::resource('/pages','Backend\PagesController');


	//Sliders
	Route::resource('/sliders','Backend\SlidersController');

	//Slide Item
	Route::put('/slides/{slide_item}','Backend\SlidersController@update_slide')->name('slides.update');

    //Photos
	Route::resource('/photos','Backend\PhotosController');


});	

app/Http/Controllers/Backend/AnalyticsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Backend\BackendController;

class AnalyticsController extends BackendController
{
     //
   public function __construct(){
        parent :: __construct();    
    }


    // D:\laragon\www\greatinfo.loc\resources\views\backend\analytics

/*
		protected $data;
	    protected $heading;
	    protected $subheading;
	    protected $vars = [];

 		 $this->heading = 'Information Panel';
   		 $this->subheading = 'Information the Site';

   		 $this->vars = array_add($this->vars,'heading',$this->heading);  
   		 $this->vars = array_add($this->vars,'subheading',$this->subheading);  

    	 return view('backend.dashboard.index')->with($this->vars );

*/


    public function index(){

    	return view('backend.analytics.index')->with($this->vars);
    } 
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Menu;
use App\Models\Page;

class BackendController extends Controller
{
    //
    protected $vars = array();

    public function __construct(){

      $this->init();
		
  	$menuMainAdmin = $this->getMenuMainAgmin(); 
  		
  	$this->vars = array_add($this->vars,'menuMainAdmin',$menuMainAdmin); 
		
		//dd($this->vars);	
	}
   
    public function init(){
     
      $pages = Page::all();
      if( isset($pages) && ($pages->count()) > 0  ){

       // dd($pages);

      }
      else {
           $config_pages = config('pages.pages');

           foreach ($config_pages as $key => $value) {
               
               $page = new Page;

               $page->name = $value['name'];
               $page->heading = $value['heading'];
               $page->template = $value['template'];
               $page->order_menu = $value['order_menu'];

               $page->save();
           } // End Foreach
      } // End Else



    }


    public function getMenuMainAgmin(){

	$result = Menu::make('MenuMainAdmin', function ($m) {
      $m->add('<i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Analytics</span>',
            	['route'  => 'analytics',
      			 'class' => 'nnav-item',
      			 'data-toggle' => 'tooltip',
      			 'data-placement' => 'right',
      			 'title' => 'Analytics',
      		 	 ])->link->attr(['class' => 'nav-link']);

	  $m->add('<i class="fa fa-fw fa-file"></i>
            <span class="nav-link-text">Pages</span>',
            	['route'  => 'pages.index',
      			 'class' => 'nnav-item',
      			 'data-toggle' => 'tooltip',
      			 'data-placement' => 'right',
      			 'title' => 'Pages',
      		 	 ])->link->attr(['class' => 'nav-link']);

    $m->add('<i class="fa fa-fw fa-photo"></i>
            <span class="nav-link-text">Photos</span>',
              ['route'  => 'photos.index',
             'class' => 'nnav-item',
             'data-toggle' => 'tooltip',
             'data-placement' => 'right',
             'title' => 'Photos',
             ])->link->attr(['class' => 'nav-link']);

   

     // $m->add('Posts',['route'  => ['posts']]);

   //  $m->add('Gallery',['route'  => 'photos']);
    //  $m->add('Settings',['route'  => 'settings']);
	});

	return $result;
    }
 
     /*
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Analytics">
          <a class="nav-link" href="{{ route('analytics')  }}">
            <i class="fa fa-lg fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Analytics</span>
          </a>
        </li>

     */



}

app/Http/Controllers/Backend/PagesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Page;
use Illuminate\Http\Request;
use App\Http\Controllers\Backend\BackendController;

class PagesController extends BackendController
{
    
     //
    public function __construct(){
        parent :: __construct();    
    }

    



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $pages = Page::all();
        $this->vars = array_add($this->vars,'pages',$pages); 

        // $slider = $pages->find(1)->slider;

        // dd($slider);

        return view('backend.pages.index')->with($this->vars);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //




        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function show(Page $page)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function edit(Page $page)
    {
        //
        $this->vars = array_add($this->vars,'page',$page); 

        $slider = $page->slider; 
        $this->vars = array_add($this->vars,'slider',$slider); 

       // dd($slider);
        
        return view('backend.pages.edit')->with($this->vars);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Page $page)
    {
        //
       if ($request->has('description') ) {
  //            
             $page->description = $request->description;
             $page->save();

             return back()->with('status', 'Updata OK!');
           
        }
        else{

            $this->validate($request, [
                'heading' => 'required|max:255',
                'name' => 'required|max:255',
                'order_menu' => 'required',
              ]);
            
            $page->heading = e($request->heading);
            $page->name = e($request->name);
            $page->order_menu = e($request->order_menu);

            $page->save();

            return back()->with('status', 'Updata OK!');


            
        }

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function destroy(Page $page)
    {
        //
    }
}

app/Http/Controllers/Backend/PhotosController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Photo;
use App\Models\Category;

use Illuminate\Support\Facades\Storage;

use Illuminate\Http\Request;
use App\Http\Controllers\Backend\BackendController;

class PhotosController extends BackendController
{
    
    //
    public function __construct(){
        parent :: __construct();    
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
     $photos = Photo::get();
     $this->vars = array_add($this->vars,'photos',$photos);

     $categories = Category::get();
     $this->vars = array_add($this->vars,'categories',$categories);

$this->vars = array_add($this->vars,'all_categories',true);
      

     
        return view('backend.photos.index')->with($this->vars); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
     $photos = [];
     $this->vars = array_add($this->vars,'photos',$photos);

     $categories = Category::get();
     
     if ( $categories->count() > 0 ) {
         $this->vars = array_add($this->vars,'categories',$categories);
     }
     else{
        $categories = [];
        $this->vars = array_add($this->vars,'categories',$categories);
     }  

     return view('backend.photos.create')->with($this->vars); 


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        echo "string  Store";
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function show(Photo $photo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function edit(Photo $photo)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Photo $photo)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Photo $photo)
    {
        //
    }
}

app/Http/Controllers/Backend/PostsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Backend\BackendController;

class PostsController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

app/Http/Controllers/Backend/SlidesController0000.php
<?php

namespace App\Http\Controllers\Backend;

use App\Slide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use App\Http\Controllers\Backend\BackendController;

class SlidesController extends BackendController
{
  
    protected  $path_image = '/public/slides';
    protected  $status_edit = true;



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $slides = Slide::all(); 

         return view('backend.slides.index')->with([
                         'slides' => $slides
                     ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
        $this->status_edit = false;
        return view('backend.slides.create')->with([
                         'status_edit' => $this->status_edit
                     ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    
            $slide = new Slide;
      
            $this->validate($request, [
                'heading' => 'required|max:255',
                'upload_img' => 'required|image',
                'description' => 'required',
              ]);

            //-------
            $upload_img = $request->file('upload_img'); 
            $ext_img = $upload_img->getClientOriginalExtension();

            $slide_img = str_random(20).'.'.$ext_img;

            $url_img = $upload_img->storeAs($this->path_image,$slide_img);
             
            $url_slide_img = Storage::url($url_img);

            //-------------

            $slide->heading = e($request->heading);
            $slide->description = e($request->description);
            $slide->slide_img = $url_slide_img;

          $slide->save(); 
           
         return redirect('admin/slides')->with('status', 'Slide Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function show(Slide $slide)
    {
        //
        echo "string";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function edit(Slide $slide)
    {

         $this->status_edit = true;
         return view('backend.slides.edit')->with([
                         'slide' => $slide,
                         'status_edit' => $this->status_edit
                     ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slide $slide)
    {
        //
        
            $this->validate($request, [
                'heading' => 'required|max:255',
                'upload_img' => 'image',
                'description' => 'required',
              ]);

            //-------
            //   dd($old_url_img);

           if ($request->hasFile('upload_img')) {

               $old_url_img = $slide->slide_img;

               $pos =  strpos($old_url_img, '/',1); 
               // "/storage/slides/slide_17.jpg"

               $puth = substr($old_url_img,  ($pos + 1));
               // "slides/slide_17.jpg"

                $exists = Storage::disk('public')->exists( $puth );

                 if( $exists ){
                    $delfiles = Storage::disk('public')->delete( $puth );
                  }
   

                $upload_img = $request->file('upload_img'); 
                $ext_img = $upload_img->getClientOriginalExtension();

                $slide_img = str_random(20).'.'.$ext_img;

                $url_img = $upload_img->storeAs($this->path_image,$slide_img);
                 
                $url_slide_img = Storage::url($url_img);

                $slide->slide_img = $url_slide_img;
            } 
            //---END if()  ---------

            $slide->heading = e($request->heading);
            $slide->description = e($request->description);
            
         $slide->save();     

         return redirect('admin/slides')->with('status', 'Slide Update!'); 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slide $slide)
    {
        //
           //

               $old_url_img = $slide->slide_img;

               $pos =  strpos($old_url_img, '/',1); 
               // "/storage/slides/slide_17.jpg"

               $puth = substr($old_url_img,  ($pos + 1));
               // "slides/slide_17.jpg"

                $exists = Storage::disk('public')->exists( $puth );

                 if( $exists ){
                    $delfiles = Storage::disk('public')->delete( $puth );
                  }
   
       
     // dd($slide)

      $result  = $slide->delete();  

      return response()->json($result);



    }
}

resources/views/backend/photos/00edit.blade.php
@extends('backend.layouts.backend')

@section('content')


  <div class="content-wrapper">
    <div class="container-fluid">

      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ route('analytics')}}"> {{ __('Analytics') }} </a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ route('pages.index') }}"> {{ __('Pages')  }}  </a>
        </li>
        <li class="breadcrumb-item active"> {{ __('Edit Page') }}  </li>
      </ol>

     


 <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> {{ __('Page '.$page->name ) }}
        </div>

         <div class="card-body">  

<div class="row">

 <div class="col-9">

     <!-- TAB General   -->
    <div class="tab-content" id="v-pills-tabContent">

      <div class="tab-pane fade show active" id="v-pills-general" role="tabpanel" aria-labelledby="v-pills-general-tab">

        <!-- Form   -->

    <form method="POST" action="{{ route('pages.update',$page) }}" enctype="multipart/form-data" >
        @csrf
        {{ method_field('PUT') }}

      <div class="form-group row">
          <label for="heading" class="col-md-4 col-form-label text-md-right">{{ __('Heading') }}</label>

          <div class="col-md-6">
              <input id="heading" type="text" class="form-control @error('heading') is-invalid @enderror" name="heading" value="{{ $page->heading }}" required autocomplete="heading" autofocus>

              @error('heading')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

      <div class="form-group row">
          <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name item Menu') }}</label>

          <div class="col-md-6">
             <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $page->name }}" required >
  
              @error('name')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

       <div class="form-group row">
          <label for="order_menu" class="col-md-4 col-form-label text-md-right">{{ __('Order in Menu') }}</label>

          <div class="col-md-6">
              <input type="range" id="order_menu" name="order_menu" min="1" max="5" value="{{ $page->order_menu }}" class=" form-control-range form-control @error('order_menu') is-invalid @enderror" name="order_menu">
  
              @error('order_menu')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

       <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
            </div>
        </div>


      </form>
 
      </div> <!-- END TAB General   -->
  

       <!--  TAB Description   -->
      <div class="tab-pane fade" id="v-pills-description" role="tabpanel" aria-labelledby="v-pills-description-tab">

         <form method="POST" action="{{ route('pages.update',$page) }}" enctype="multipart/form-data" >
        @csrf
        {{ method_field('PUT') }}

      <div class="form-group row">
          <label for="description" class="col-md-3 col-form-label text-md-right">{{ __('Description') }}</label>

          <div class="col-md-8">
              <textarea  id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="5" >{{ $page->description }}</textarea>

              @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>
      <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-3">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
            </div>
        </div>
     </form>

      </div>   <!-- END TAB Description   -->

       <!-- TAB Slider   -->
      <div class="tab-pane fade" id="v-pills-slider" role="tabpanel" aria-labelledby="v-pills-slider-tab">


 
      <p>
         <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#form_add_slide_item" aria-expanded="false" aria-controls="form_add_slide_item">  {{ __('Add New Slide') }} </button>
      </p>

    

  <div id="form_add_slide_item"  class="row border border-primary  mx-2 my-2 bg-light text-dark collapse ">
       

        <div class="col-md-6 offset-md-3 my-2">
           <img  id="image_file"  class="img-thumbnail" src="{{asset('storage/img/portfolio/2.jpg') }}" alt="" >
        </div>   

        <div class="col-md-10 offset-md-1 my-2">

  @if(isset($slider) && ($slider->count()) > 0)

       <form method="POST" action="{{ route('sliders.update',$slider) }}" enctype="multipart/form-data" >
            {{ method_field('PUT') }}

  @else  

        <form method="POST" action="{{ route('sliders.store') }}" enctype="multipart/form-data" >

  @endif  


          @csrf

            <input type="hidden" name="page" value="{{$page->id}}">
        
          <div class="form-group">
            <label for="heading">{{ __('Image for slide') }}</label>
         
            <input id="upload_img" type="file" class="form-control-file"  name="upload_img" required autocomplete="upload_img">

                  @error('upload_img')
                    <p><span style="margin-top: .25rem; font-size: .875rem; color: #dc3545;">
                      <strong>{{ $message }}</strong>
                    </span></p>
                  @enderror
          </div>

          <div class="form-group">
            <label for="heading">{{ __('Heading') }}</label>
         
           <input id="heading" type="text" class="form-control @error('heading') is-invalid @enderror" name="heading" value="{{ old('heading') }}" autocomplete="heading">

              @error('heading')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>


          <div class="form-group">
            <label for="description">{{ __('Description') }}</label>
         
            <textarea  id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="3" >{{ old('description') }}</textarea>

              @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

        
          <div class="form-group my-1">
            
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
                 <button type="reset" class="btn btn-secondary">
                    {{ __('Cansel') }}
                </button>
            
          </div>
     </form>

        </div> 
      </div> <!--  /.row   --> 

    <!--   ////////-------------- -->


      
   

 
 @if(isset($slider) && ($slider->count()) > 0)


      



      <div class="card card-body">
      <div class="row">

@foreach( $slider->slide_items as $slide_item )

       {{-- ////***************  --}}


<div id="form_edit_slide_item_{{ $slide_item->id }}"  class="row border border-primary  mx-2 my-2 bg-light text-dark collapse ">
       

        <div class="col-md-6 offset-md-3 my-2">
           <img  id="file_edit"  class="img-thumbnail" src="{{asset( $slide_item->image ) }}" alt="" >
        </div>   

        <div class="col-md-10 offset-md-1 my-2">

  @if(isset($slider) && ($slider->count()) > 0)

       <form method="POST" action="{{ route('slides.update',$slide_item) }}" enctype="multipart/form-data" >
            {{ method_field('PUT') }}

  @else  

        
  @endif  


          @csrf

            <input type="hidden" name="page" value="{{$page->id}}">
        
          <div class="form-group">
            <label for="heading">{{ __('Image for slide EDIT') }}</label>
         
            <input id="upload_img" type="file" class="form-control-file"  name="upload_img" required autocomplete="upload_img">

                  @error('upload_img')
                    <p><span style="margin-top: .25rem; font-size: .875rem; color: #dc3545;">
                      <strong>{{ $message }}</strong>
                    </span></p>
                  @enderror
          </div>

          <div class="form-group">
            <label for="heading">{{ __('Heading') }}</label>
         
           <input id="heading" type="text" class="form-control @error('heading') is-invalid @enderror" name="heading" value="{{ $slide_item->heading }}" autocomplete="heading">

              @error('heading')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>


          <div class="form-group">
            <label for="description">{{ __('Description') }}</label>
         
            <textarea  id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="3" >{{ $slide_item->description }}</textarea>

              @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

        
          <div class="form-group my-1">
            
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
                 <button type="reset" class="btn btn-secondary">
                    {{ __('Cansel') }}
                </button>
            
          </div>
     </form>

        </div> 
      </div> <!--  /.row   --> 



        <div class="col-md-3 my-1">

         <a data-toggle="collapse" href="#form_edit_slide_item_{{ $slide_item->id }}"  aria-expanded="false" aria-controls="form_edit_slide_item_{{ $slide_item->id }}">
  
           <img class="img-thumbnail" src="{{asset($slide_item->image) }}" alt="" >
          </a>

        </div>






        @endforeach 
     
      </div> <!--  /.row   -->
      
     
      
      </div> <!--  /.card card-body   -->
          

      @else
          <p>  Not Slide </p> 

       @endif 


      </div> <!-- END TAB Slider   -->
      
    </div>
  </div>

  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">

      <a class="nav-link active" id="v-pills-general-tab" data-toggle="pill" href="#v-pills-general" role="tab" aria-controls="v-pills-general" aria-selected="true">General</a>

      <a class="nav-link" id="v-pills-description-tab" data-toggle="pill" href="#v-pills-description" role="tab" aria-controls="v-pills-description" aria-selected="false">Description</a>

      <a class="nav-link" id="v-pills-slider-tab" data-toggle="pill" href="#v-pills-slider" role="tab" aria-controls="v-pills-slider" aria-selected="false">Slider</a>

      <a class="nav-link" id="v-pills-go_to_pages-tab" href="{{ route('pages.index') }}" role="tab" aria-controls="v-pills-go_to_pages" aria-selected="false">Go to Pages </a>
    </div>
  </div>
 
</div>
 </div> <!-- /.card-body -->
 </div><!-- /.card -->



    </div>
  </div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
  
@endsection

    
 @push('script_Change_Image')

  <script src="{{asset('backend')}}/js/change-image.js"></script>
  
@endpush

		

resources/views/backend/photos/create.blade.php
@extends('backend.layouts.backend')

@section('content')

<div class="content-wrapper">
  <div class="container-fluid">


     <!-- Breadcrumbs-->
       <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ route('analytics')  }}">{{ __('Analytics') }}</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ route('photos.index')  }}">{{ __('Photos') }}</a>
        </li>
        <li class="breadcrumb-item active">Photo</li>
      </ol>
      <!-- END Breadcrumbs-->





 <div class="  my-1 ">

  <div class="card card-body">
   <div class="row">
    <div class="col-3">
      <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseFormAddCategory" aria-expanded="false" aria-controls="collapseFormAddCategory"> {{ __('Add Category')  }}</button>
      
    </div>  {{-- /.col-3 --}}
    <div class="col-9 collapse" id="collapseFormAddCategory">
      
        <form method="POST" action="{{ route('photos.store') }}" class="form-inline">
           @csrf
          
          <div class="form-group mx-sm-3">
            <label for="add_category" class="sr-only">Add Category</label>
            <input type="text" class="form-control" id="add_category" placeholder="Category Name">
          </div>
          <button type="submit" class="btn btn-primary">OK</button>
        </form>

    </div> {{-- /.col-9 --}}
   </div> {{-- /.row --}}


<div class=" mb-2 ">
  
</div>

<div class="collapse " id="collapseExample">
  <div class="">

     

  </div>
</div>

</div>

</div>


  
    
  <form method="POST" action="{{ route('photos.store') }}" enctype="multipart/form-data" >
        @csrf
      
    

       @include('backend.photos._photo_form') 


  </form> 


  </div>
</div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
  
@endsection

    


		